# NetworkBuster Cloud Run Configuration
runtime: python312
entrypoint: gunicorn -b :$PORT network_map_viewer:app

env_variables:
  PYTHON_VERSION: "3.12"
  
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
