# NetworkBuster Save and Cleanup Script
# Simple and reliable version

$ProjectRoot = "C:\Users\daypi\networkbuster.net"
Set-Location $ProjectRoot

Write-Host "`n════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  NETWORKBUSTER SAVE & CLEANUP SYSTEM" -ForegroundColor Cyan  
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Cyan

# PHASE 1: Cleanup
Write-Host "`n[1/4] Cleaning temporary files..." -ForegroundColor Yellow

$cleaned = 0
$freed = 0

# Clean node_modules cache
if (Test-Path "node_modules\.cache") {
    $size = (Get-ChildItem "node_modules\.cache" -Recurse | Measure-Object -Property Length -Sum).Sum
    Remove-Item "node_modules\.cache" -Recurse -Force -ErrorAction SilentlyContinue
    $freed += $size
    $cleaned++
    Write-Host "  ✓ Removed node_modules cache" -ForegroundColor Green
}

# Clean Python cache
Get-ChildItem -Path $ProjectRoot -Recurse -Include "__pycache__","*.pyc" -Force -ErrorAction SilentlyContinue | ForEach-Object {
    $freed += $_.Length
    Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
    $cleaned++
}
Write-Host "  ✓ Cleaned Python cache files" -ForegroundColor Green

# Clean log files
Get-ChildItem -Path $ProjectRoot -Include "*.log" -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
    if ($_.Length -gt 0) {
        $freed += $_.Length
        Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue
        $cleaned++
    }
}
Write-Host "  ✓ Cleaned log files" -ForegroundColor Green

$freedMB = [math]::Round($freed / 1MB, 2)
Write-Host "  Summary: $cleaned items removed, ${freedMB} MB freed" -ForegroundColor White

# PHASE 2: Git Save
Write-Host "`n[2/4] Saving to Git..." -ForegroundColor Yellow

$hasGit = Get-Command git -ErrorAction SilentlyContinue
if ($hasGit -and (Test-Path ".git")) {
    $status = git status --porcelain
    if ($status) {
        git add -A
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
        git commit -m "Auto-save: Update and cleanup - $timestamp"
        Write-Host "  ✓ Changes committed to git" -ForegroundColor Green
    } else {
        Write-Host "  ✓ No changes to commit" -ForegroundColor Green
    }
} else {
    Write-Host "  ⚠ Git not available" -ForegroundColor Yellow
}

# PHASE 3: Backup to drives
Write-Host "`n[3/4] Backing up to available drives..." -ForegroundColor Yellow

$drives = Get-PSDrive -PSProvider FileSystem | Where-Object { 
    $_.Used -ne $null -and $_.Name -ne 'C' -and $_.Free -gt 1GB 
}

if ($drives) {
    $timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"
    $backupName = "NetworkBuster_$timestamp"
    
    foreach ($drive in $drives) {
        $backupPath = Join-Path $drive.Root "Backups\$backupName"
        
        try {
            Write-Host "  Backing up to $($drive.Name):..." -ForegroundColor Cyan
            
            # Create backup directory
            New-Item -ItemType Directory -Path $backupPath -Force | Out-Null
            
            # Copy important files (excluding large directories)
            $exclude = @("node_modules", ".git", ".venv", "__pycache__")
            
            Get-ChildItem -Path $ProjectRoot -Exclude $exclude | ForEach-Object {
                Copy-Item $_.FullName -Destination $backupPath -Recurse -Force -ErrorAction SilentlyContinue
            }
            
            $backupSize = (Get-ChildItem $backupPath -Recurse | Measure-Object -Property Length -Sum).Sum
            $sizeMB = [math]::Round($backupSize / 1MB, 2)
            
            Write-Host "  ✓ Backup complete ($sizeMB MB) -> $backupPath" -ForegroundColor Green
        } catch {
            Write-Host "  ✗ Backup failed: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
} else {
    Write-Host "  ⚠ No additional drives available" -ForegroundColor Yellow
}

# PHASE 4: Generate Report
Write-Host "`n[4/4] Generating report..." -ForegroundColor Yellow

$reportDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$report = @"
# Save & Cleanup Report
**Date:** $reportDate

## Cleanup
- Files cleaned: $cleaned
- Space freed: ${freedMB} MB

## Git
- Status: $(if ($hasGit -and (Test-Path ".git")) { "Saved" } else { "Skipped" })

## Backups
- Drives: $($drives.Count)
- Folder: $backupName

## Project
- Path: $ProjectRoot
- Total drives scanned: $((Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Used -ne $null }).Count)

---
*Generated by NetworkBuster Save & Cleanup System*
"@

$report | Out-File -FilePath "SAVE_CLEANUP_REPORT.md" -Encoding UTF8
Write-Host "  ✓ Report saved to SAVE_CLEANUP_REPORT.md" -ForegroundColor Green

# Final Summary
Write-Host "`n════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  ✅ ALL OPERATIONS COMPLETE" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "`nCleaned: $cleaned items (${freedMB} MB)" -ForegroundColor White
Write-Host "Git: $(if ($hasGit -and (Test-Path '.git')) { 'Saved' } else { 'Skipped' })" -ForegroundColor White
Write-Host "Backups: $($drives.Count) drive(s)" -ForegroundColor White
Write-Host ""
