#!/usr/bin/env bash
# Hardened network boost for Linux
# Usage: sudo ./network-boost.sh [--apply] [--no-confirm] [--persist]
# - --apply: apply recommended changes
# - --no-confirm: don't prompt
# - --persist: also write to /etc/sysctl.d/99-networkbuster.conf
#
# Examples:
#   # Dry run to show recommended changes
#   ./network-boost.sh
#   # Apply interactively (prompts for confirmation)
#   sudo ./network-boost.sh --apply
#   # Apply without prompts and persist across reboots
#   sudo ./network-boost.sh --apply --no-confirm --persist
#   # Non-interactive (CI or automation)
#   sudo ./network-boost.sh --apply --no-confirm
#
# Notes:
# - After applying a restore script is generated: network-boost-restore.sh
# - Logs are appended to network-boost.log
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG="$DIR/network-boost.log"
RESTORE="$DIR/network-boost-restore.sh"

recommendations=(
  "net.core.rmem_max=16777216"
  "net.core.wmem_max=16777216"
  "net.ipv4.tcp_window_scaling=1"
  "net.ipv4.tcp_congestion_control=bbr"
)

apply=false
no_confirm=false
persist=false

for arg in "$@"; do
  case $arg in
    --apply) apply=true ;; 
    --no-confirm) no_confirm=true ;; 
    --persist) persist=true ;; 
    *) echo "Unknown arg: $arg"; exit 1 ;;
  esac
done

echo "Starting Linux Network Boost (apply=$apply). Log: $LOG"

echo "# Network boost log - $(date -u)" >> "$LOG"

echo "Recommended changes:"
for r in "${recommendations[@]}"; do echo "  $r"; done

if [ "$apply" = false ]; then
  echo "Dry run - no changes applied. Use --apply to apply changes."; exit 0
fi

if [ "$no_confirm" = false ]; then
  read -rp "Apply recommended changes now? (y/N): " ans
  case "$ans" in
    y|Y|yes|Yes) ;;
    *) echo "Cancelled by user."; exit 0 ;;
  esac
fi

# Create restore script
cat > "$RESTORE" <<'REST'
#!/usr/bin/env bash
# Restore previous sysctl values (generated by network-boost.sh)
set -euo pipefail
REST
chmod +x "$RESTORE"

# capture current values and append restore commands
for r in "${recommendations[@]}"; do
  key="${r%%=*}"
  newval="${r#*=}"
  oldval=$(sysctl -n "$key" 2>/dev/null || echo "")
  echo "# $key previous: $oldval" >> "$LOG"
  if [ -n "$oldval" ]; then
    echo "sysctl -w $key=$oldval" >> "$RESTORE"
  else
    echo "# No previous value for $key" >> "$RESTORE"
  fi
done

# apply changes
for r in "${recommendations[@]}"; do
  echo "Setting $r" | tee -a "$LOG"
  sysctl -w "$r" | tee -a "$LOG"
done

if [ "$persist" = true ]; then
  conffile="/etc/sysctl.d/99-networkbuster.conf"
  echo "Persisting settings to $conffile" | tee -a "$LOG"
  tmpfile="/tmp/99-networkbuster.conf.$$"
  for r in "${recommendations[@]}"; do echo "$r" >> "$tmpfile"; done
  sudo mv "$tmpfile" "$conffile"
  sudo sysctl --system | tee -a "$LOG"
  echo "Persisted settings" >> "$LOG"
fi

echo "Network boost applied. Restore with: $RESTORE" | tee -a "$LOG"
exit 0
